module.exports = {
  obsConnected: false,
  activeScene: "",
  isStreaming: false,
  streamBitrate: 0,
  isRecording: false,
  sourcesConnected: { "Tail A": false, "Tail B": false, "Mobile SRT": false },
  autoSwitch: { enabled: false, mobile: false, min: 5, max: 15 },
  ytAuthenticated: false,
  ytVideoId: null,
  ytLiveChatId: null,
  ytStreamTitle: "",
  ytBroadcastStatus: null,
  ytIsCreating: false,
  ytIsTransitioning: false,
  ytStreamHealth: "noData",
  ytStreamStatus: "inactive",
  ytErrorMessage: "",
};
